### ISSUE TITLE
Discord Thread compatibility

### ISSUE THREAD

**Issue by fbrettnich** [easypoll-bot/easypoll-java#5]
Make bot compatible with the new [Discord Threads](https://discord.com/developers/docs/topics/threads)
Currently, commands where reactions are added end with "This interaction failed"

```
java.lang.IllegalStateException: Cannot convert channel of type UNKNOWN to MessageChannel
    at net.dv8tion.jda.api.interactions.Interaction.getMessageChannel(Interaction.java:430)
    at net.dv8tion.jda.internal.interactions.InteractionHookImpl.sendRequest(InteractionHookImpl.java:156)
    at net.dv8tion.jda.internal.entities.AbstractWebhookClient.sendMessageEmbeds(AbstractWebhookClient.java:67)
    at net.dv8tion.jda.internal.entities.AbstractWebhookClient.sendMessageEmbeds(AbstractWebhookClient.java:40)
    at net.dv8tion.jda.api.entities.WebhookClient.sendMessageEmbeds(WebhookClient.java:170)
    at de.fbrettnich.easypoll.commands.PollCommand.<init>(PollCommand.java:157)
    at de.fbrettnich.easypoll.listener.SlashCommandListener.onSlashCommand(SlashCommandListener.java:63)
    at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:481)
    at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
    at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
    at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
    at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160)
    at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:75)
    at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:59)
    at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
    at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
    at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
    at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
    at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990)
    at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
    at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
    at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
    at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
    at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
    at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
    at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)```

**Comment by fbrettnich** [comment]
Polls are still not compatible with Discord Threads, waiting for an update from [JDA](https://github.com/DV8FromTheWorld/JDA/)

All commands work, except for:
- the full Poll/TimePoll Command
- a feedback on the ClosePoll command (poll is closed, but there is no feedback)
Identifiable by the fact that it permanently says "EasyPoll is thinking..."
